openapi: 3.0.0
info:
  description:
    API для доступа к данным по господдержке
  version: "1.0.0-oas3"
  title: ГОСПОДДЕРЖКА
  contact:
    email: ah@fond-kino.ru
paths:
  /login:
    post:
      tags:
        - 'login'
      summary: Выполняет процедуру аутентификации и возвращает объект пользователя
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResult'
        '401': 
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
        '500': 
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        description: Объект запроса
        required: true
  /ktpub-api/rating/movies:
    get:
      summary: Возвращает рейтинг фильмов вышедших в прокат
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Номер страницы
        - in: query
          name: per_page
          schema:
            type: integer
          description: Кол-во записей на странице
        - in: query
          name: sortType
          schema:
            type: string
          description: Название атрибута по которому сортировать. Прим:: Для сортировки по названию компании передпть "company"
        - in: query
          name: sort
          schema:
            type: string
          description: Направление сортировки:: ASC - по возрастанию, DESC - по убыванию
        - in: query
          name: support_id
          schema:
            type: integer
          description: ID источника финансирования
        - in: query
          name: search_query
          schema:
            type: string
          description: Строка поиска по имени фильма или по названию студии
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MoviePrj'
        '401':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'

  /ktpub-api/projects/inProduction:
    get:
      summary: Возвращает проэкты в производстве
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Номер страницы
        - in: query
          name: per_page
          schema:
            type: integer
          description: Кол-во записей на странице
        - in: query
          name: sortType
          schema:
            type: string
          description: Название атрибута по которому сортировать. Прим:: Для сортировки по названию компании передпть "company"
        - in: query
          name: sort
          schema:
            type: string
          description: Направление сортировки:: ASC - по возрастанию, DESC - по убыванию
        - in: query
          name: support_id
          schema:
            type: integer
          description: ID источника финансирования
        - in: query
          name: search_query
          schema:
            type: string
          description: Строка поиска по имени фильма или по названию студии
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MoviePrj'
        '401':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'

  /ktpub-api/projects/unfulfilledObligations:
    get:
      summary: Возвращает неисполненные обязательства
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Номер страницы
        - in: query
          name: per_page
          schema:
            type: integer
          description: Кол-во записей на странице
        - in: query
          name: sortType
          schema:
            type: string
          description: Название атрибута по которому сортировать. Прим:: Для сортировки по названию компании передпть "company"
        - in: query
          name: sort
          schema:
            type: string
          description: Направление сортировки:: ASC - по возрастанию, DESC - по убыванию
        - in: query
          name: support_id
          schema:
            type: integer
          description: ID источника финансирования
        - in: query
          name: search_query
          schema:
            type: string
          description: Строка поиска по имени фильма или по названию студии
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MoviePrj'
        '401':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'

  /ktpub-api/rating/companies:
    get:
      summary: Возвращает рэейтиг компаний
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          description: Номер страницы
        - in: query
          name: per_page
          schema:
            type: integer
          description: Кол-во записей на странице
        - in: query
          name: sortType
          schema:
            type: string
          description: Название атрибута по которому сортировать. Прим:: Для сортировки по названию проекта/фильма передпть "movie"
        - in: query
          name: sort
          schema:
            type: string
          description: Направление сортировки:: ASC - по возрастанию, DESC - по убыванию
        - in: query
          name: support_id
          schema:
            type: integer
          description: ID источника финансирования
        - in: query
          name: release_status
          schema:
            type: integer
          description: Статус проката (1 - в прокате, 2 - в производстве, без параметра - все)
        - in: query
          name: search_query
          schema:
            type: string
          description: Строка поиска по имени фильма или по названию студии
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MoviePrj'
        '401':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'

servers:
  - url: 'http://mkesb.sapi.fond-kino.ru:8083/sapi/rest'
components:
  schemas:
    LoginRequest: 
      type: object
      properties:
        login:
          type: string
          description: Аутентификационные данные в формате login/password
    ErrorResult:
      type: object
      properties:
        success: 
          type: boolean
          description:  false - ошибка
        exception:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      properties:
        errCode:
          type: integer
          format: int32
        message:
          type: string
          description: Сообщение сервера
    LoginResult:
      type: object
      properties:
        success: 
          type: boolean
          description:  true - все ок
        user:
          $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        anonymous:
          type: boolean
          description: Если true, то пользователь - аноним
        email:
          type: string
          description: email пользователя
        fio:
          type: string
          description: ФИО пользователя
        grants: 
          type: string
          description: Список идентификаторов грантов через зпт
        login: 
          type: string
          description: Имя пользователя
        orgDesc: 
          type: string
          description: Описание организации пользователя
        orgId:
          type: string
          description: ID организации пользователя
        orgName: 
          type: string
          description: Название организации пользователя
        phone: 
          type: string
          description: Контактный телефон
        roles:
          type: string
          description: Список идентификаторов ролей через зпт
        stoken: 
          type: string
          description: Токен сессии, передается в заголовок всех запросов S-Token. Перманентный. Жив пока не сделаешь logoff

    FinancingSource:
      type: object
      description: Источник финансирования
      properties:
        id:
          type: number
          description: Идентификатор
        name:
          type: string
          description: Название
        short_name:
          type: string
          description: Краткое обозначение
        image:
          type: string
          description: Ссылка на иконку

    PrjName:
      type: object
      description: Название компании в списке
      properties:
        id:
          type: string
          description: ОГРН
        name:
          type: string
          description: Название компании
        financing_source:
          type: array
          items:
            $ref: '#/components/schemas/FinancingSource'

    Company:
      type: object
      description: Название компании в списке
      properties:
        id:
          type: string
          description: ОГРН
        index_number:
          type: number
          description: Номер по порядку
        name:
          type: string
          description: Название компании
        total_movies:
          type: number
          description: Всего проектов/фильмов
        refundable_support:
          type: string
          description: Возвратные средства
        nonrefundable_support:
          type: string
          description: Безвозвратные средства
        box_office:
          type: string
          description: Сборы
        audience:
          type: string
          description: Зрители
        movies:
          type: array
          items:
            $ref: '#/components/schemas/PrjName'

    CompanyName:
      type: object
      description: Название компании в списке
      properties:
        id:
          type: string
          description: ОГРН
        name:
          type: string
          description: Название компании


    MoviePrj:
      type: object
      description: Проэкт в прокате/произсводстве/неисполненные обязательства
      properties:
        total_companies:
          type: number
          description: всего компаний, которые учавствовали в производстве проекта
        id:
          type: string
          description: Идентификатор проэкта
        puNumber:
          type: string
          description: Номер ПУ
        index_number:
          type: string
          description: Номер по порядку
        name:
          type: string
          description: Название фильма/проекта
        release_date:
          type: string
          description: Дата выхода в прокат
        refundable_support:
          type: string
          description: Возвратные средства
        nonrefundable_support:
          type: string
          description: Безвозвратные средства
        percent_support:
          type: string
          description: Процент поддержки
        budget:
          type: string
          description: Бюджет
        box_office:
          type: string
          description: Сборы
        audience:
          type: string
          description: Зрители
        financing_source:
          type: array
          items:
            $ref: '#/components/schemas/FinancingSource'
        companies:
          type: array
          items:
            $ref: '#/components/schemas/CompanyName'

    MoviesRating:
      type: object
      properties:
        movies:
          type: array
          items:
            $ref: '#/components/schemas/MoviePrj'
        total_movies:
          type: number
          description: Всего проектов/фильмов
        total_companies:
          type: number
          description: Всего компаний
        total_refundable_support:
          type: number
          description: Всего возвратных средств
        total_nonrefundable_support:
          type: number
          description: Всего безвозвратных средств
        total_budget:
          type: number
          description: Всего бюджет
        total_box_office:
          type: number
          description: Всего сборов
        total_audience:
          type: number
          description: Всего зрителей

    CompaniesRating:
      type: object
      properties:
        companies:
          type: array
          items:
            $ref: '#/components/schemas/Company'
        total_movies:
          type: number
          description: Всего проектов/фильмоа
        total_companies:
          type: number
          description: Всего компаний
        total_refundable_support:
          type: string
          description: Всего возвратных средств
        total_nonrefundable_support:
          type: string
          description: Всего безвозвратных средств
        total_box_office:
          type: string
          description: Всего сборов
        total_audience:
          type: string
          description: Всего зрителей
