openapi: 3.0.0
info:
  description: |
    API для мобильного приложения ЕАИС
  version: "1.0.0-oas3"
  title: Мост кинотека-еаис
  contact:
    email: ah@fond-kino.ru
tags:
  - name: eais
    description: ЕАИС
  #Все методы вызывать так /pub.aspx?auth_token=<auth_token>&method=<имя мнетода>&<параметры>
paths:
  # *******************************************************************************************************************
  /auth:
    post:
      summary: Выполняет процедуру аутентификации и возвращает объект пользователя
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/User'
        '401': 
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500': 
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: 'ekb-common-1.0.0.yaml#/components/schemas/LoginRequest'
        description: Объект запроса
        required: true
  # *******************************************************************************************************************
  /authGuest:
    post:
      summary: Выполняет процедуру аутентификации и возвращает объект пользователя для Гостя
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/User'
        '401':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: 'ekb-common-1.0.0.yaml#/components/schemas/LoginRequestGuest'
        description: Объект запроса
        required: true
  # *******************************************************************************************************************
  /getFilmAnalog1:
    get:
      summary: Возвращает фильмы-аналоги для заданного фильма в заданном периоде
      parameters:
        - in: path
          name: idFilm
          schema:
            type: string
          required: true
          description: ПУ фильма
        - in: path
          name: idInterval
          schema:
            type: string
          required: true
          description: ID интервала - значение атрибута "id" из результата запроса "getFilmAnalogInterval"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Film'
        '401': 
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500': 
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
  # *******************************************************************************************************************
  /getFilmAnalogInterval:
    get:
      summary: Возвращает список доступных интервалов для конкретного фильма
      parameters:
        - in: path
          name: idFilm
          schema:
            type: string
          required: true
          description: ПУ фильма
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AnalogInterval'
        '401':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
  # *******************************************************************************************************************
  /storeMyFilms:
    post:
      summary: Сохраняет добавленные вручную ПУ для аналогов
      responses:
        '200':
          description: Если сохранение прошло без ошибок, то возвращается этот объект
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    default: 'OK'
        '401':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AnalogManualFolder'
        description: Объект запроса
        required: true
  # *******************************************************************************************************************
  /resetMyFilms:
    post:
      summary: Очищает папку добавленных вручную ПУ для аналогов
      responses:
        '200':
          description: Если очистка прошла без ошибок, то возвращается этот объект
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    default: 'OK'
        '401':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                folder:
                  type: string
                  description: Название папки, которую нужно очистить
        description: Объект запроса
        required: true
  # *******************************************************************************************************************
  /weekends:
    get:
      summary: Возвращает список уикендов за выбранный год
      parameters:
        - in: path
          name: year
          schema:
            type: string
          required: true
          description: Год в формате YYYY
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Weekend'
        '401':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'

  # *******************************************************************************************************************
  /search:
    get:
      summary: Возвращает список фильмов
      parameters:
        - in: path
          name: currId
          schema:
            type: integer
          description: Код валюты в которой будут возвращаться все суммы, 0-руб, 1-доллар США, 2-евро, по умолчанию 0.
        - in: path
          name: rlocale
          schema:
            type: string
          description: В какой локали возвращать данные, 'ru'-русский, 'en'-английский, по умолчанию 'ru'
        - in: path
          name: query
          schema:
            type: string
          description: Строка поиска по названию(рус/англ) или по номеру ПУ (ищет вхождение не зависимо от регистра)
        - in: path
          name: sort
          schema:
            type: string
          description: по какому полю сортировать money|tickets|seances. Если не указано и указан query, то сортируется по дате выхода в прокат, если query не указан, то по money
        - in: path
          name: onlyFilmsOlderThenTheNoon
          schema:
            type: string
          description: 1-если фильм вышел в прокат сегодня и еще не настало 12:00, но он не будем возвращаться в результат
        - in: path
          name: moviesOnly
          schema:
            type: string
          description: 1-возвращать только фильмы которые в прокате, если последний сеанс фильма был более 1 суток назад, то фильм не будем возвращаться в результат
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Film'
        '401':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
  # *******************************************************************************************************************
  /pub.aspx?method=top:
    get:
      summary: Возвращает топ фильмов
      parameters:
        - in: path
          name: currId
          schema:
            type: integer
          description: Код валюты в которой будут возвращаться все суммы, 0-руб, 1-доллар США, 2-евро, по умолчанию 0.
        - in: path
          name: rlocale
          schema:
            type: string
          description: В какой локали возвращать данные, 'ru'-русский, 'en'-английский, по умолчанию 'ru'
        - in: path
          name: region
          schema:
            type: string
          description: Фильтр по коду региона, можно передавать список кодов через зпт
        - in: path
          name: sort
          schema:
            type: string
          description: по какому полю сортировать money|tickets|seances. Если не указано и указан query, то сортируется по дате выхода в прокат, если query не указан, то по money
        - in: path
          name: qmode
          schema:
            type: string
          description: 1-дополнительно вычисляет поля sumByDateFinish, но похоже это уже  не используется
        - in: path
          name: onlyFilmsOlderThenTheNoon
          schema:
            type: string
          description: 1-если фильм вышел в прокат сегодня и еще не настало 12:00, но он не будем возвращаться в результат
        - in: path
          name: withMyFilms
          schema:
            type: string
          description: 1-возвращает дополнительно фильмы, которые выбраны вручную пользователем
        - in: path
          name: fkonly
          schema:
            type: string
          description: 1-возврвщает данные только по поддержанным кинозалам (доступно только пользователям с грантом 210)
        - in: path
          name: periodStart
          schema:
            type: string
          description: Начало периода за который собранны данные в полях sum, quantity, sessions, moneyPerSession, ticketsPerSession
        - in: path
          name: periodEnd
          schema:
            type: string
          description: Окончание периода за который собранны данные в полях sum, quantity, sessions, moneyPerSession, ticketsPerSession
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Film'
        '401':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
  # *******************************************************************************************************************
  /pub.aspx?method=:
    get:
      summary: Возвращает топ фильмов
      parameters:
        - in: path
          name: currId
          schema:
            type: integer
          description: Код валюты в которой будут возвращаться все суммы, 0-руб, 1-доллар США, 2-евро, по умолчанию 0.
        - in: path
          name: rlocale
          schema:
            type: string
          description: В какой локали возвращать данные, 'ru'-русский, 'en'-английский, по умолчанию 'ru'
        - in: path
          name: region
          schema:
            type: string
          description: Фильтр по коду региона, можно передавать список кодов через зпт
        - in: path
          name: sort
          schema:
            type: string
          description: по какому полю сортировать money|tickets|seances. Если не указано и указан query, то сортируется по дате выхода в прокат, если query не указан, то по money
        - in: path
          name: qmode
          schema:
            type: string
          description: 1-дополнительно вычисляет поля sumByDateFinish, но похоже это уже  не используется
        - in: path
          name: onlyFilmsOlderThenTheNoon
          schema:
            type: string
          description: 1-если фильм вышел в прокат сегодня и еще не настало 12:00, но он не будем возвращаться в результат
        - in: path
          name: withMyFilms
          schema:
            type: string
          description: 1-возвращает дополнительно фильмы, которые выбраны вручную пользователем
        - in: path
          name: fkonly
          schema:
            type: string
          description: 1-возврвщает данные только по поддержанным кинозалам (доступно только пользователям с грантом 210)
        - in: path
          name: periodStart
          schema:
            type: string
          description: Начало периода за который собранны данные в полях sum, quantity, sessions, moneyPerSession, ticketsPerSession
        - in: path
          name: periodEnd
          schema:
            type: string
          description: Окончание периода за который собранны данные в полях sum, quantity, sessions, moneyPerSession, ticketsPerSession
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Film'
        '401':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
servers:
  - url: 'https://ekinobilet.ru/ekbapi'
    description: боевой сервер
  - url: 'https://ekinobilet.ru/ekbapi2'
    description: тестовый сервер
components:
  schemas:

    Weekend:
      type: object
      description: Уикенд
      properties:
        id:
          type: integer
          description: ID уикенда в формате YYYYNN, где YYYY-год, NN-номер уикенда в году
        dateStart:
          type: string
          description: Начало уикенда в формате YYYY-MM-DD"T"HH:mm:ss
        dateEnd:
          type: string
          description: Окончание уикенда в формате YYYY-MM-DD"T"HH:mm:ss

    AnalogInterval:
      type: object
      description: Интервал для построения массива фильмов-аналогов
      properties:
        id:
          type: string
          description: ID интервала
        desc:
          type: string
          description: Название интервала

    AnalogManualFolder:
      type: object
      description: Папка для сохранения выбранных ПУ для аналогов
      properties:
        folder:
          type: string
          description: ID папки
        pus:
          description: Список ПУ
          type: array
          items:
            type: string
