openapi: 3.0.0
info:
  description: |
    API для мобильного приложения ЕАИС
  version: "1.0.0-oas3"
  title: Мост кинотека-еаис
  contact:
    email: ah@fond-kino.ru
paths:

components:
  schemas:
    LoginRequest:
      type: object
      properties:
        login:
          type: string
          description: Имя пользователя
        password:
          type: string
          description: Пароль

    Error:
      type: object
      properties:
        errorCode:
          type: integer
          format: int32
        message:
          type: string
          description: Сообщение сервера
    User:
      type: object
      properties:
        auth_token:
          type: string
          description: Токен сессии, передается во все запросы параметром auth_token. Перманентный. Жив пока не сделаешь logoff
        company:
          type: string
          description: Название организации, к которой относится пользователь
        roles:
          type: string
          description: Список ролей пользователья (разделитель ',')
        grants:
          type: string
          description: Список разрешений (разделитель ',')
        role:
          type: integer
          description: Роль  пользователя (осталось для совместимости со старыми приложениями)
        org_id:
          type: string
          description: ID организации, к которой относится пользователь
        ip:
          type: string
          description: IP адрес, пользователя
        type:
          type: integer
          description: Тип пользователя (устаревший атрибут)
        push:
          type: boolean
          description: Если true, то разрешены push уведомления (пока не используется)
        pushtoken:
          type: string
          description: Для push уведомлений
    Film:
      type: object
      properties:
        id:
          type: string
          description: Номер ПУ
        title:
          type: string
          description: Название фильма
        title_en:
          type: string
          description: Название фильма (англ)
        year:
          type: string
          description: Год выхода на экран
        country:
          type: string
          description: Страна
        country_en:
          type: string
          description: Страна (англ)
        owner:
          type: string
          description: Правообладатель
        owner_en:
          type: string
          description: Правообладатель (англ)
        description:
          type: string
          description: Описание
        description_en:
          type: string
          description: Описание (англ)
        launch_date:
          type: string
          description: Дата выхода на экраны (в формате YYYY.MM.DD'T'HH:mm:ss, например '2019.01.01T00:00:00')
        genre:
          type: string
          description: Список жанров
        genre_en:
          type: string
          description: Список жанров (англ)
        genreids:
          type: array
          items:
            type: integer
          description: Список id жанров (если они есть в справочнике)
        ageRestrictions:
          type: string
          description: Воразстные ограничения
        ageRestrictions_en:
          type: string
          description: Воразстные ограничения (англ)
        ageRestr:
          type: integer
          description: Воразстные ограничения
        forecastFK:
          type: string
          description: Прогноз Фонда Кино
        forecastDist:
          type: string
          description: Прогноз Дистрибьютора
        forecastBK:
          type: string
          description: Прогноз БК
        forecast4:
          type: string
          description: Прогноз №4
        isFollowed:
          type: boolean
          description: Фильм в прокате
        director:
          type: string
          description: Режисеры
        director_en:
          type: string
          description: Режисеры (англ)
        screenwriter:
          type: string
          description: Сценаристы
        screenwriter_en:
          type: string
          description: Сценаристы (англ)
        producer:
          type: string
          description: Продюссеры
        producer_en:
          type: string
          description: Продюссеры (англ)
        distributor:
          type: string
          description: Правообладатели (по реестру МКРФ)
        distributor_en:
          type: string
          description: Правообладатели (по реестру МКРФ) (англ)
        starring:
          type: string
          description: В ролях
        rating:
          type: string
          description: В ролях (англ)
        heading:
          type: string
          description: Какой-то рудимент
        distributorId:
          type: string
          description: Список ID дистрибьюторов (разделитель ',')
        money0:
          type: number
          description: Сборы за весь период проката (служебный атрибут)
        money0_en:
          type: number
          description: Сборы за весь период проката в usd (служебный атрибут)
        money0_eu:
          type: number
          description: Сборы за весь период проката в euro (служебный атрибут)
        tickets0:
          type: integer
          description: Зрителей посмотрело за весь период проката (служебный атрибут)
        seances0:
          type: integer
          description: Сеансов за весь период проката (служебный атрибут)
        money:
          type: number
          description: Сборы за весь период проката
        money_en:
          type: number
          description: Сборы за весь период проката в usd
        money_eu:
          type: number
          description: Сборы за весь период проката в euro
        tickets:
          type: integer
          description: Зрителей посмотрело за весь период проката
        seances:
          type: integer
          description: Сеансов за весь период проката
        presales:
          type: number
          description: Предпродажи
        presales_en:
          type: number
          description: Предпродажи в usd
        presales_eu:
          type: number
          description: Предпродажи в euro
        presalesStart:
          type: string
          description: Начало предпродаж (в формате YYYY.MM.DD'T'HH:mm:ss, например '2019.01.01T00:00:00')
        presalesEnd:
          type: string
          description: Окончание предпродаж (в формате YYYY.MM.DD'T'HH:mm:ss, например '2019.01.01T00:00:00')
        launchDateSales:
          type: number
          description: Сборы в день старта
        launchDateSales_en:
          type: number
          description: Сборы в день старта в usd
        launchDateSales_eu:
          type: number
          description: Сборы в день старта в euro
        firstWeekendDateStart:
          type: string
          description: Дата начала первого уикенда (в формате YYYY.MM.DD'T'HH:mm:ss, например '2019.01.01T00:00:00')
        firstWeekendDateFinish:
          type: string
          description: Дата окончания первого уикенда (в формате YYYY.MM.DD'T'HH:mm:ss, например '2019.01.01T00:00:00')
        firstWeekendSales:
          type: string
          description: Сборы в первый уикенд
        firstWeekendSales_en:
          type: string
          description: Сборы в первый уикенд в usd
        firstWeekendSales_eu:
          type: string
          description: Сборы в первый уикенд в euro
        secondWeekendDateStart:
          type: string
          description: Дата начала вторго уикенда (в формате YYYY.MM.DD'T'HH:mm:ss, например '2019.01.01T00:00:00')
        secondWeekendDateFinish:
          type: string
          description: Дата окончания вторго уикенда (в формате YYYY.MM.DD'T'HH:mm:ss, например '2019.01.01T00:00:00')
        secondWeekendSales:
          type: string
          description: Сборы в первый уикенд
        secondWeekendSales_en:
          type: string
          description: Сборы в первый уикенд в usd
        secondWeekendSales_eu:
          type: string
          description: Сборы в первый уикенд в euro
        generalSalesDateFinish:
          type: string
          description: Дата окончания общих сборов
        dateStart:
          type: string
          description: Начало периода за который собранны данные в полях sum, quantity, sessions, moneyPerSession, ticketsPerSession
        dateFinish:
          type: string
          description: Окончание периода за который собранны данные в полях sum, quantity, sessions, moneyPerSession, ticketsPerSession
        dsum:
          type: string
          description: Для аналогов - это разность между суммой сборов оригинального фильма и его аналогом (для оригинала тут будет 0)
        sum:
          type: string
          description: Сумма сборов за выбранный период
        sum_en:
          type: string
          description: Сумма сборов за выбранный период в usd
        sum_eu:
          type: string
          description: Сумма сборов за выбранный период в euro
        quantity:
          type: string
          description: Кол-во зрителей которые посмотрели фильм за выбранный период
        sessions:
          type: string
          description: Кол-во сеансов за выбранный период
        moneyPerSession:
          type: string
          description: Сборы на севнс за выбранный период
        moneyPerSession_en:
          type: string
          description: Сборы на севнс за выбранный период в usd
        moneyPerSession_eu:
          type: string
          description: Сборы на севнс за выбранный период в euro
        ticketsPerSession:
          type: string
          description: Зрителей на сеанс
        percentageSalesFK:
          type: string
          description: процент сборов в поддержанных кинозалах
        percentageTicketsFK:
          type: string
          description: процент зрителей в поддержанных кинозалах
        percentageSeansesFK:
          type: string
          description: процент сеансов в поддержанных кинозалах
        posterBig:
          type: string
          description: Ссылка на большой постер
        posterSmall:
          type: string
          description: Ссылка на малый постер
        posterBig_en:
          type: string
          description: Ссылка на большой постер (англ)
        posterSmall_en:
          type: string
          description: Ссылка на малый постер (англ)
        sumByDateFinish:
          type: string
          description: Cумма сборов с начала проката по dateFinish
        sumByDateFinish_en:
          type: string
          description: Cумма сборов с начала проката по dateFinish в usd
        sumByDateFinish_eu:
          type: string
          description: Cумма сборов с начала проката по dateFinish в euro
        showdays:
          type: string
          description: кол-во дней в прокате
        previewFrom:
          type: string
          description: Дата начала предпоказов
        previewTo:
          type: string
          description: Дата окончания предпоказов
        previewSumm:
          type: string
          description: Сумма сборов на предпоказах
        previewSumm_en:
          type: string
          description: Сумма сборов на предпоказах в usd
        previewSumm_eu:
          type: string
          description: Сумма сборов на предпоказах в euro
        previewTickets:
          type: string
          description: Кол-во зрителей на предпоказах
        previewSessions:
          type: string
          description: Кол-во сеансов на предпоказах

    CompStatRequest:
      type: object
      required: ["compId","compName","pus"]
      properties:
        compId:
          type: integer
          description: ID компании
        compName:
          type: string
          description: Название компании
        pus:
          type: string
          description: 'Список ПУ (разделитель ",")'
    CompStat:
      type: object
      description: Статистика по компании (все данные возвращаются за выбранный период)
      properties:
        ktcompId:
          type: integer
          format: int64
          description: ID компании
        fkTcktsReturn00:
          type: integer
          format: int64
          description: зрители по безвозвратным проектам
        fkTcktsReturn01:
          type: integer
          format: int64
          description: зрители по возвратным проектам
        fkTcktsReturn11:
          type: integer
          format: int64
          description: зрители по 100% возвратным проектам
        fkTcktsTotal:
          type: integer
          format: int64
          description: зрители по проектам ФК
        fkSessReturn00:
          type: integer
          format: int64
          description: сеансы по безвозвратным проектам
        fkSessReturn01:
          type: integer
          format: int64
          description: сеансы по возвратным проектам
        fkSessReturn11:
          type: integer
          format: int64
          description: сеансы по 100% возвратным проектам
        fkSessTotal:
          type: integer
          format: int64
          description: сеансы по проектам ФК
        fkSummReturn00:
          type: number
          format: money
          description: сборы по безвозвратным проектам
        fkSummReturn01:
          type: number
          format: money
          description: сборы по возвратным проектам
        fkSummReturn11:
          type: number
          format: money
          description: сборы по 100% возвратным проектам
        fkSummTotal:
          type: number
          format: money
          description: сборы по проектам ФК
        fkFilmsReturn00:
          type: integer
          format: int64
          description: фильмов по безвозвратным проектам
        fkFilmsReturn01:
          type: integer
          format: int64
          description: фильмов по возвратным проектам
        fkFilmsReturn11:
          type: integer
          format: int64
          description: фильмов по 100% возвратным проектам
        fkFilmsTotal:
          type: integer
          format: int64
          description: фильмов по проектам ФК
        tcktsTotal:
          type: integer
          format: int64
          description: зрителей по компании
        sessTotal:
          type: integer
          format: int64
          description: сеансов по компании
        summTotal:
          type: number
          format: money
          description: сборы по компании
        filmsTotal:
          type: integer
          format: int64
          description: фильмов по компании
    FilmsStatRequest:
      type: object
      required: ["pus"]
      properties:
        periodFrom:
          type: string
          description: Начало запрашиваемого периода
          format: YYYY-MM-DD
        periodTo:
          type: string
          description: Конец запрашиваемого периода
          format: YYYY-MM-DD
        pus:
          type: string
          description: 'Список ПУ (разделитель ",")'
    
    FilmStat:
      type: object
      description: Статистика по фильму
      properties:
        puNum:
          type: string
          description: Номер ПУ
        filmName:
          type: string
          description: Название фильма
        tcktsTotal:
          type: integer
          format: int64
          description: зрителей по фильму за выбранный период
        sessTotal:
          type: integer
          format: int64
          description: сеансов по фильму за выбранный период
        summTotal:
          type: number
          format: money
          description: сборы по фильму за выбранный период