openapi: 3.0.0
info:
  description: |
    API для доступа к данным ЕАИС из внешних систем
  version: "1.0.0-oas3"
  title: Мост кинотека-еаис
  contact:
    email: ah@fond-kino.ru
tags:
  - name: mkesb
    description: Шина МКРФ
  - name: kinoteka
    description: Кинотека
  - name: eais
    description: ЕАИС
paths:
  /login:
    post:
      tags:
        - 'login'
      summary: Выполняет процедуру аутентификации и возвращает объект пользователя
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResult'
        '401': 
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
        '500': 
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        description: Объект запроса
        required: true
  /api/kinoteka/comp-stat:
    post:
      tags:
        - 'company,statistics'
      summary: Возвращает статистику по компании
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CompStat'
        '401': 
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
        '500': 
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompsStatRequest'
        description: Объект запроса
        required: true
  /api/kinoteka/film-stat:
    post:
      tags:
        - 'film,statistics'
      summary: Возвращает статистику по фильмам
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FilmStat'
        '401': 
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
        '500': 
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilmsStatRequest'
        description: Объект запроса
        required: true
servers:
  - url: 'http://mkesb.sapi.fond-kino.ru:8083/sapi/rest'
components:
  schemas:
    LoginRequest: 
      type: object
      properties:
        login:
          type: string
          description: Аутентификационные данные в формате login/password
    ErrorResult:
      type: object
      properties:
        success: 
          type: boolean
          description:  false - ошибка
        exception:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      properties:
        errCode:
          type: integer
          format: int32
        message:
          type: string
          description: Сообщение сервера
    LoginResult:
      type: object
      properties:
        success: 
          type: boolean
          description:  true - все ок
        user:
          $ref: '#/components/schemas/User'
    User:
      type: object
      properties:
        anonymous:
          type: boolean
          description: Если true, то пользователь - аноним
        email:
          type: string
          description: email пользователя
        fio:
          type: string
          description: ФИО пользователя
        grants: 
          type: string
          description: Список идентификаторов грантов через зпт
        login: 
          type: string
          description: Имя пользователя
        orgDesc: 
          type: string
          description: Описание организации пользователя
        orgId:
          type: string
          description: ID организации пользователя
        orgName: 
          type: string
          description: Название организации пользователя
        phone: 
          type: string
          description: Контактный телефон
        roles:
          type: string
          description: Список идентификаторов ролей через зпт
        stoken: 
          type: string
          description: Токен сессии, передается в заголовок всех запросов S-Token. Перманентный. Жив пока не сделаешь logoff 
  
  
    CompsStatRequest:
      type: object
      required: ["comps"]
      properties:
        periodFrom:
          type: string
          description: Начало запрашиваемого периода
          format: YYYY-MM-DD
        periodTo:
          type: string
          description: Конец запрашиваемого периода
          format: YYYY-MM-DD
        comps:
          type: array
          items:
            $ref: '#/components/schemas/CompStatRequest'
    CompStatRequest:
      type: object
      required: ["compId","compName","pus"]
      properties:
        compId:
          type: integer
          description: ID компании
        compName:
          type: string
          description: Название компании
        pus:
          type: string
          description: 'Список ПУ (разделитель ",")'
    CompStat:
      type: object
      description: Статистика по компании (все данные возвращаются за выбранный период)
      properties:
        ktcompId:
          type: integer
          format: int64
          description: ID компании
        fkTcktsReturn00:
          type: integer
          format: int64
          description: зрители по безвозвратным проектам
        fkTcktsReturn01:
          type: integer
          format: int64
          description: зрители по возвратным проектам
        fkTcktsReturn11:
          type: integer
          format: int64
          description: зрители по 100% возвратным проектам
        fkTcktsTotal:
          type: integer
          format: int64
          description: зрители по проектам ФК
        fkSessReturn00:
          type: integer
          format: int64
          description: сеансы по безвозвратным проектам
        fkSessReturn01:
          type: integer
          format: int64
          description: сеансы по возвратным проектам
        fkSessReturn11:
          type: integer
          format: int64
          description: сеансы по 100% возвратным проектам
        fkSessTotal:
          type: integer
          format: int64
          description: сеансы по проектам ФК
        fkSummReturn00:
          type: number
          format: money
          description: сборы по безвозвратным проектам
        fkSummReturn01:
          type: number
          format: money
          description: сборы по возвратным проектам
        fkSummReturn11:
          type: number
          format: money
          description: сборы по 100% возвратным проектам
        fkSummTotal:
          type: number
          format: money
          description: сборы по проектам ФК
        fkFilmsReturn00:
          type: integer
          format: int64
          description: фильмов по безвозвратным проектам
        fkFilmsReturn01:
          type: integer
          format: int64
          description: фильмов по возвратным проектам
        fkFilmsReturn11:
          type: integer
          format: int64
          description: фильмов по 100% возвратным проектам
        fkFilmsTotal:
          type: integer
          format: int64
          description: фильмов по проектам ФК
        tcktsTotal:
          type: integer
          format: int64
          description: зрителей по компании
        sessTotal:
          type: integer
          format: int64
          description: сеансов по компании
        summTotal:
          type: number
          format: money
          description: сборы по компании
        filmsTotal:
          type: integer
          format: int64
          description: фильмов по компании
    FilmsStatRequest:
      type: object
      required: ["pus"]
      properties:
        periodFrom:
          type: string
          description: Начало запрашиваемого периода
          format: YYYY-MM-DD
        periodTo:
          type: string
          description: Конец запрашиваемого периода
          format: YYYY-MM-DD
        pus:
          type: string
          description: 'Список ПУ (разделитель ",")'
    
    FilmStat:
      type: object
      description: Статистика по фильму
      properties:
        puNum:
          type: string
          description: Номер ПУ
        filmName:
          type: string
          description: Название фильма
        tcktsTotal:
          type: integer
          format: int64
          description: зрителей по фильму за выбранный период
        sessTotal:
          type: integer
          format: int64
          description: сеансов по фильму за выбранный период
        summTotal:
          type: number
          format: money
          description: сборы по фильму за выбранный период