openapi: 3.0.0
info:
  description: |
    API для мобильного приложения ЕАИС
  version: "1.0.0-oas3"
  title: Мост кинотека-еаис
  contact:
    email: ah@fond-kino.ru
tags:
  - name: eais
    description: ЕАИС
paths:
  /pub.aspx?method=auth:
    post:
      summary: Выполняет процедуру аутентификации и возвращает объект пользователя
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/User'
        '401': 
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500': 
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: 'ekb-common-1.0.0.yaml#/components/schemas/LoginRequest'
        description: Объект запроса
        required: true
  /pub.aspx?method=getFilmAnalog1:
    post:
      tags:
        - 'analog'
      summary: Возвращает фильмы-аналоги для заданного фильма в заданном периоде
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CompStat'
        '401': 
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
        '500': 
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompsStatRequest'
        description: Объект запроса
        required: true
  /api/kinoteka/film-stat:
    post:
      tags:
        - 'film,statistics'
      summary: Возвращает статистику по фильмам
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FilmStat'
        '401': 
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
        '500': 
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResult'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FilmsStatRequest'
        description: Объект запроса
        required: true
servers:
  - url: 'https://ekinobilet.ru/ekbapi'
    description: боевой сервер
  - url: 'https://ekinobilet.ru/ekbapi2'
    description: тестовый сервер
components:
  schemas:

    FilmStat:
      type: object
      description: Статистика по фильму
      properties:
        puNum:
          type: string
          description: Номер ПУ
        filmName:
          type: string
          description: Название фильма
        tcktsTotal:
          type: integer
          format: int64
          description: зрителей по фильму за выбранный период
        sessTotal:
          type: integer
          format: int64
          description: сеансов по фильму за выбранный период
        summTotal:
          type: number
          format: money
          description: сборы по фильму за выбранный период