openapi: 3.0.0
info:
  description: |
    API для мобильного приложения ЕАИС
  version: "1.0.0-oas3"
  title: Мост кинотека-еаис
  contact:
    email: ah@fond-kino.ru
tags:
  - name: eais
    description: ЕАИС
paths:
  /pub.aspx?method=auth:
    post:
      summary: Выполняет процедуру аутентификации и возвращает объект пользователя
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/User'
        '401': 
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500': 
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: 'ekb-common-1.0.0.yaml#/components/schemas/LoginRequest'
        description: Объект запроса
        required: true
  /pub.aspx?method=getFilmAnalog1:
    get:
      summary: Возвращает фильмы-аналоги для заданного фильма в заданном периоде
      parameters:
        - in: path
          name: idFilm
          schema:
            type: string
          required: true
          description: ПУ фильма
        - in: path
          name: idInterval
          schema:
            type: string
          required: true
          description: ID интервала - значение атрибута "id" из результата запроса "getFilmAnalogInterval"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Film'
        '401': 
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500': 
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'

  /pub.aspx?method=getFilmAnalogInterval:
    get:
      summary: Возвращает список доступных интервалов для конкретного фильма
      parameters:
        - in: path
          name: idFilm
          schema:
            type: string
          required: true
          description: ПУ фильма
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AnalogInterval'
        '401':
          description: Ошибка аутентификации
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'
        '500':
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: 'ekb-common-1.0.0.yaml#/components/schemas/Error'

servers:
  - url: 'https://ekinobilet.ru/ekbapi'
    description: боевой сервер
  - url: 'https://ekinobilet.ru/ekbapi2'
    description: тестовый сервер
components:
  schemas:

    AnalogInterval:
      type: object
      description: Интервал для построения массива фильмов-аналогов
      properties:
        id:
          type: string
          description: ID интервала
        desc:
          type: string
          description: Название интервала
